### ISSUE TITLE
B{p,q}的计算公式有误

### ISSUE THREAD

**Issue by hhhhaww** [xumy29/Graphcut#1]
`tmp = -1 * np.sum(np.power(self.image[y, x] - self.image[y, x+1], 2) / 2)`
按照论文中的公式，/2是不是应该放在np.sum()外面？
`tmp = -1 * np.sum(np.power(self.image[y, x] - self.image[y, x+1], 2)) / 2`

**Comment by xumy29** [comment]
是的，按照公式应该写成下面的语句，不过两者结果是一样的。

**Comment by hhhhaww** [comment]
感谢您的代码，graph cut困扰了我一天，看您的代码再结合论文终于搞懂了

**Comment by xumy29** [comment]
不客气，很高兴能对你有帮助^^
不过我只是参考了论文里面的边权设置方法，没有复现完整方法，效果还是比原论文差很多的。
